### PR TITLE
Add replicas

### PR DESCRIPTION
**Pull request by EzryStIago**
Closes issue #8 : U_nk save/load
Closes issue #32 : replicas

### CODE REVIEW

**Review by jhenin — COMMENTED** [review]
Looks great! I've changed the variable name `filename_regex` for precision, because a glob pattern is not the same as a regex.
To test the replica code, I've replicated the sample data trivially using symlinks. It's working as expected, except one thing I don't understand on the per-window deltaG curve:
image

What are these gray lines that deviate from the main data?

**Comment by EzryStIago** [comment]
> What are these gray lines that deviate from the main data?

@jhenin Those are the forward and backward exponential estimates. They look gray because each replica gets alpha<1 and a different color. I'll have to think about a better way to present this. Maybe we don't really need the exponential estimates? Or we could make them a flag.

**Comment by jhenin** [comment]
I see. I think these plots are useful, but they should be documented, probably in a legend.

**Comment by EzryStIago** [comment]
I've added a legend to that plot:
image

**Review by jhenin — APPROVED** [review]
With a minor fix that I just pushed, this works well.
Ideally, a sample dataset with different data in the replicas would be nice to have, but it's not a show-stopper.

**Pull request merged**
